# Generated by Django 5.2.4 on 2025-08-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0002_alter_allergy_allergyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='category',
        ),
    ]
